### ISSUE TITLE
The "Export to CSV" as coming soon in README.md

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelitt/launchpage-rails#12]
What was meant on README.md file in:

![5367656011005952](https://cloud.githubusercontent.com/assets/1529246/8369566/3504d264-1b92-11e5-9a01-0b94f3ba0988.png)

When in UserController already have the method to export as CSV? 

app/controllers/users_controller.rb
![csv_export](https://cloud.githubusercontent.com/assets/1529246/8369577/66a28000-1b92-11e5-900c-5363ef1f62ba.png)

**Comment by codelitt** [comment]
Ahhh. Coming soon was referring to the two points below which have not been built yet. Sorry. That's mostly a formatting issue.

**Comment by kaiomagalhaes** [comment]
I got it, did you reopen the issue by accident? =D

**Comment by codelitt** [comment]
Whoops
