### ISSUE TITLE
Ideas for: post signup survey and questionaire

### ISSUE THREAD

**Issue by kaiomagalhaes** [codelitt/launchpage-rails#13]
What is the best way to gather more information from the possible users, considering that we need it simple and fast for the startup customize.

Maybe add a link after the subscribe for a survey and the startup implement his own way( The cheapest I think is google form)

**Comment by codelitt** [comment]
Ya. That is very MVP and easy to do for sure.

**Comment by codelitt** [comment]
For now and staying true to MVP, this merge closes this issue.
