### ISSUE TITLE
Create CI and CodeClimante coverage from the main repo

### ISSUE THREAD

**Issue by avinoth** [codelitt/launchpage-rails#18]
Currently the CI and Codeclimate coverage is configured for @kaiomagalhaes fork. Need to configure it to this repo. And add automatic CI for every Pull request.

https://codeclimate.com/github/kaiomagalhaes/launchpage-rails/coverage

**Comment by kaiomagalhaes** [comment]
@avinoth Yeah I had forgot. I will configure for this repo right now!

**Comment by kaiomagalhaes** [comment]
@avinoth as promised! :grin:
https://github.com/codelitt/launchpage-rails/pull/19

**Comment by avinoth** [comment]
@kaiomagalhaes :+1: We'll close it as soon as the branch merged

**Comment by kaiomagalhaes** [comment]
Closing after #19 is merged :grinning:
